spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:db
    username: pedro
    password:

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
